# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


  flutter_application_path = "../flutter_more/"
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'SealTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  # Pods for SealTalk

  install_all_flutter_pods(flutter_application_path)
  
  pod "BQMM"
  
  pod 'XZQRCode_OC'
  pod 'libqrencode'

end

target 'SealTalkShareExtension' do
  # Comment the next line if you don't want to use dynamic frameworks


  # Pods for SealTalkShareExtension

end

